import type { Metadata } from "next";
// import styles from "./styles/Home.module.css"


import "./globals.css";




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="redhat"
      >
        
        {children}
      </body>
    </html>
  );
}
